# 端口号
server:
  port: 8001

spring:
  application:
    # 服务名
    name: spring-cloud-alibaba-provider

  cloud:
    # Nacos Server的地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在 yaml 文件属于关键字，所以需要加引号